/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.rejestracjailogowanie;

import com.sun.source.doctree.AttributeTree;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author zalman
 */
public class RejestracjaILogowanie extends javax.swing.JFrame {

    /**
     * Creates new form RejestracjaILogowanie
     */
    public RejestracjaILogowanie() {
        initComponents();
        addKeyListenerTojTextFieldUsernameRejestracja();
        addKeyListenerTojTextFieldEmailRejestracja();
        addKeyListenerTojPasswordFieldRejestracja();
        addKeyListenerTojConfirmPasswordFieldRejestracja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmailZaloguj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonZaloguj = new javax.swing.JButton();
        jPasswordFieldLogowanie = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsernameRejestracja = new javax.swing.JTextField();
        jTextFieldEmailRejestracja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonRejestracja = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelZleDaneRejestracja = new javax.swing.JLabel();
        jPasswordFieldRejestracja = new javax.swing.JPasswordField();
        jConfirmPasswordFieldRejestracja = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("LOGOWANIE");

        jTextFieldEmailZaloguj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Password");

        jButtonZaloguj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonZaloguj.setText("ZALOGUJ");
        jButtonZaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZalogujActionPerformed(evt);
            }
        });

        jPasswordFieldLogowanie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldEmailZaloguj, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jButtonZaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldLogowanie))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEmailZaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addComponent(jPasswordFieldLogowanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonZaloguj)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Logowanie", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        jTextFieldUsernameRejestracja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldEmailRejestracja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password");

        jButtonRejestracja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRejestracja.setText("REJESTRACJA");
        jButtonRejestracja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRejestracjaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("REJESTRACJA");

        jLabelZleDaneRejestracja.setBackground(new java.awt.Color(255, 255, 255));
        jLabelZleDaneRejestracja.setForeground(new java.awt.Color(255, 255, 255));
        jLabelZleDaneRejestracja.setText("Wprowadzono źle dane | Wprowadź poprawnie dane");

        jPasswordFieldRejestracja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jConfirmPasswordFieldRejestracja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsernameRejestracja, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEmailRejestracja)
                    .addComponent(jLabel6)
                    .addComponent(jButtonRejestracja)
                    .addComponent(jLabel2)
                    .addComponent(jLabelZleDaneRejestracja)
                    .addComponent(jPasswordFieldRejestracja)
                    .addComponent(jConfirmPasswordFieldRejestracja))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelZleDaneRejestracja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUsernameRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldEmailRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(14, 14, 14)
                .addComponent(jPasswordFieldRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(jConfirmPasswordFieldRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRejestracja)
                .addGap(26, 26, 26))
        );

        jTabbedPane2.addTab("Rejestracja", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRejestracjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRejestracjaActionPerformed
        String username = jTextFieldUsernameRejestracja.getText();
        String password = String.valueOf(jPasswordFieldRejestracja.getPassword());
        String confirmPassword = String.valueOf(jConfirmPasswordFieldRejestracja.getPassword());
        String email = jTextFieldEmailRejestracja.getText();
        if(username.length() >= 2 && username.length() <= 20 && password.length() >= 4 && password.equals(confirmPassword) ){
            int at = email.indexOf("@");
           
            
            if(at > 1){
            jLabelZleDaneRejestracja.setForeground(Color.white);
            saveToFile();
            }
            else{
                   jLabelZleDaneRejestracja.setForeground(Color.red); 
                    }
        }
        else{
            jLabelZleDaneRejestracja.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButtonRejestracjaActionPerformed

    private void jButtonZalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZalogujActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonZalogujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RejestracjaILogowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RejestracjaILogowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RejestracjaILogowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RejestracjaILogowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RejestracjaILogowanie().setVisible(true);
            }
        });
    }
    
    private void addKeyListenerTojTextFieldUsernameRejestracja(){
        jTextFieldUsernameRejestracja.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char znak = e.getKeyChar();
                if(znak >= 65 && znak<= 90 || znak>=97 && znak<=122 || znak == KeyEvent.VK_BACK_SPACE ){
                    jTextFieldUsernameRejestracja.setEditable(true);
                }
                else{
                    jTextFieldUsernameRejestracja.setEditable(false);
                } 
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    } 
    private void addKeyListenerTojTextFieldEmailRejestracja(){
        jTextFieldEmailRejestracja.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char znak = e.getKeyChar();
                if(znak >= 65 && znak<= 90 || znak>=97 && znak<=122 ||
                znak>=48 && znak<=57 || znak == 46 || znak == 64 || znak == KeyEvent.VK_BACK_SPACE ){
                    jTextFieldEmailRejestracja.setEditable(true);
                    
                }
                else{
                    jTextFieldEmailRejestracja.setEditable(false);
                }
                    
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
               
            }
        });
    }
    private void  addKeyListenerTojPasswordFieldRejestracja(){
        jPasswordFieldRejestracja.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char znak = e.getKeyChar();
                if(znak >=  48 && znak<=57 || znak >= 65 && znak<=90 || znak>=97 && znak<=122 || znak == KeyEvent.VK_BACK_SPACE){
                    jPasswordFieldRejestracja.setEditable(true);
                }               
                else{
                    jPasswordFieldRejestracja.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    private void addKeyListenerTojConfirmPasswordFieldRejestracja(){
            jConfirmPasswordFieldRejestracja.addKeyListener(new KeyListener() {
                @Override
                public void keyTyped(KeyEvent e) {
                   
                    char znak = e.getKeyChar();
                    if(znak >=  48 && znak<=57 || znak >= 65 && znak<=90 || znak>=97 && znak<=122 || znak == KeyEvent.VK_BACK_SPACE){    
                        jConfirmPasswordFieldRejestracja.setEditable(true);
                    }
                    else{
                        jConfirmPasswordFieldRejestracja.setEditable(false);
                    }
                }

                @Override
                public void keyPressed(KeyEvent e) {
                    
                }

                @Override
                public void keyReleased(KeyEvent e) {
                    
                }
            });
    }
    private void saveToFile(){
        String fileName = "sekretnehasla.csv";
        File file = new File(fileName);
        String username = jTextFieldUsernameRejestracja.getText();
        String email = jTextFieldEmailRejestracja.getText();
        String password = String.valueOf(jPasswordFieldRejestracja.getPassword());
        jTextFieldUsernameRejestracja.setText("");
        jTextFieldEmailRejestracja.setText("");
        jPasswordFieldRejestracja.setText("");
        jConfirmPasswordFieldRejestracja.setText("");
        try {
            FileWriter fw = new FileWriter(fileName,true);
            fw.write(username+":"+email+":"+password+"\n");
            fw.close();
            
        } catch (IOException e) {
            System.out.println(e);
        }
    } 
    
    private void jOptionPane(){
        jTextFieldUsernameRejestracja.setToolTipText("Wpisz nazwe uzytkownika 2-20 znakow tylko litery");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRejestracja;
    private javax.swing.JButton jButtonZaloguj;
    private javax.swing.JPasswordField jConfirmPasswordFieldRejestracja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelZleDaneRejestracja;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordFieldLogowanie;
    private javax.swing.JPasswordField jPasswordFieldRejestracja;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldEmailRejestracja;
    private javax.swing.JTextField jTextFieldEmailZaloguj;
    private javax.swing.JTextField jTextFieldUsernameRejestracja;
    // End of variables declaration//GEN-END:variables
}
