/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projektwlasnyprogram;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author zalman
 */
public class ProjektProgram extends javax.swing.JFrame {

    /**
     * Creates new form ProjektProgram
     */
    public ProjektProgram() {
        initComponents();
        nf_jLabelLogo.setIcon(new ImageIcon(AbsolutePathToResources));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nf_buttonGroupKlasa = new javax.swing.ButtonGroup();
        nf_jPanel1 = new javax.swing.JPanel();
        nf_jLabelImie = new javax.swing.JLabel();
        nf_jLabelNazwisko = new javax.swing.JLabel();
        nf_jLabelSzkola = new javax.swing.JLabel();
        nf_jLabelKierunek = new javax.swing.JLabel();
        nf_jLabelKlasa = new javax.swing.JLabel();
        nf_jTextFieldImie = new javax.swing.JTextField();
        nf_jTextFieldNazwisko = new javax.swing.JTextField();
        nf_jComboBoxSzkola = new javax.swing.JComboBox<>();
        nf_jComboBoxKierunek = new javax.swing.JComboBox<>();
        nf_jRadioButton1 = new javax.swing.JRadioButton();
        nf_jRadioButton2 = new javax.swing.JRadioButton();
        nf_jRadioButton3 = new javax.swing.JRadioButton();
        nf_jRadioButton4 = new javax.swing.JRadioButton();
        nf_jRadioButton5 = new javax.swing.JRadioButton();
        nf_jLabel7LiczbaUczniow = new javax.swing.JLabel();
        nf_jSliderLiczbaUczniow = new javax.swing.JSlider();
        nf_ScrollPane1 = new javax.swing.JScrollPane();
        nf_jTextAreaWczytaneDane = new javax.swing.JTextArea();
        nf_jLabelZapisaneDane = new javax.swing.JLabel();
        nf_jLabelLogo = new javax.swing.JLabel();
        nf_menubar = new javax.swing.JMenuBar();
        nf_Plik = new javax.swing.JMenu();
        nf_Zapisz = new javax.swing.JMenuItem();
        nf_Wczytaj = new javax.swing.JMenuItem();
        nf_Zamknij = new javax.swing.JMenuItem();
        nf_Edycja = new javax.swing.JMenu();
        nf_ZmienCzcionke = new javax.swing.JMenuItem();
        nf_ZmienTlo = new javax.swing.JMenu();
        nf_tloNiebieski = new javax.swing.JMenuItem();
        nf_tloZielony = new javax.swing.JMenuItem();
        nf_tloBialy = new javax.swing.JMenuItem();
        nf_tloDefault = new javax.swing.JMenuItem();
        nf_OProgramie = new javax.swing.JMenu();
        nf_OProgramieMeniuItem = new javax.swing.JMenuItem();
        nf_Help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Szkolne Dane Uczniów Nowa Sól");
        setName("FrameProgram"); // NOI18N

        nf_jPanel1.setBackground(new java.awt.Color(128, 128, 128));

        nf_jLabelImie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nf_jLabelImie.setText("Imie");

        nf_jLabelNazwisko.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nf_jLabelNazwisko.setText("Nazwisko");

        nf_jLabelSzkola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nf_jLabelSzkola.setText("Szkoła");

        nf_jLabelKierunek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nf_jLabelKierunek.setText("Kierunek");

        nf_jLabelKlasa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nf_jLabelKlasa.setText("Klasa");

        nf_jTextFieldImie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        nf_jTextFieldNazwisko.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        nf_jComboBoxSzkola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nf_jComboBoxSzkola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LO Baczyński", "CKZIU ELEKTRYK", "ZSP 4 \"SPOŻYWCZAK\"", "ZSP 5 w Kożuchowie" }));
        nf_jComboBoxSzkola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_jComboBoxSzkolaActionPerformed(evt);
            }
        });

        nf_jComboBoxKierunek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nf_jComboBoxKierunek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Logistyka", "Ekonomia", "Matfiz", "Informatyka", "Programistyka" }));

        nf_buttonGroupKlasa.add(nf_jRadioButton1);
        nf_jRadioButton1.setText("1");

        nf_buttonGroupKlasa.add(nf_jRadioButton2);
        nf_jRadioButton2.setText("2");

        nf_buttonGroupKlasa.add(nf_jRadioButton3);
        nf_jRadioButton3.setText("3");

        nf_buttonGroupKlasa.add(nf_jRadioButton4);
        nf_jRadioButton4.setText("4");

        nf_buttonGroupKlasa.add(nf_jRadioButton5);
        nf_jRadioButton5.setText("5");

        nf_jLabel7LiczbaUczniow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nf_jLabel7LiczbaUczniow.setText("Liczba uczniów");

        nf_jSliderLiczbaUczniow.setMajorTickSpacing(5);
        nf_jSliderLiczbaUczniow.setMaximum(35);
        nf_jSliderLiczbaUczniow.setMinorTickSpacing(1);
        nf_jSliderLiczbaUczniow.setPaintLabels(true);
        nf_jSliderLiczbaUczniow.setPaintTicks(true);
        nf_jSliderLiczbaUczniow.setSnapToTicks(true);
        nf_jSliderLiczbaUczniow.setToolTipText("");
        nf_jSliderLiczbaUczniow.setValue(17);

        nf_jTextAreaWczytaneDane.setColumns(20);
        nf_jTextAreaWczytaneDane.setRows(5);
        nf_ScrollPane1.setViewportView(nf_jTextAreaWczytaneDane);

        nf_jLabelZapisaneDane.setText("Zapisane Dane");

        nf_jLabelLogo.setIcon(new ImageIcon(AbsolutePathToResources + "LogoProgramu.png"));

        javax.swing.GroupLayout nf_jPanel1Layout = new javax.swing.GroupLayout(nf_jPanel1);
        nf_jPanel1.setLayout(nf_jPanel1Layout);
        nf_jPanel1Layout.setHorizontalGroup(
            nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nf_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                        .addComponent(nf_jLabelImie)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanel1Layout.createSequentialGroup()
                                        .addComponent(nf_jLabelNazwisko)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nf_jTextFieldImie, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nf_jTextFieldNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nf_jLabelSzkola)
                                    .addComponent(nf_jLabelKlasa)
                                    .addComponent(nf_jLabelKierunek))
                                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nf_jRadioButton2)
                                            .addComponent(nf_jRadioButton1)
                                            .addComponent(nf_jRadioButton3)
                                            .addComponent(nf_jRadioButton4)
                                            .addComponent(nf_jRadioButton5)))
                                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nf_jComboBoxKierunek, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nf_jComboBoxSzkola, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanel1Layout.createSequentialGroup()
                                .addComponent(nf_jLabelZapisaneDane)
                                .addGap(208, 208, 208))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanel1Layout.createSequentialGroup()
                                .addComponent(nf_jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                        .addComponent(nf_jLabel7LiczbaUczniow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nf_jSliderLiczbaUczniow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(nf_ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        nf_jPanel1Layout.setVerticalGroup(
            nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanel1Layout.createSequentialGroup()
                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nf_jLabelImie)
                            .addComponent(nf_jTextFieldImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nf_jTextFieldNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf_jLabelNazwisko))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nf_jComboBoxSzkola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf_jLabelSzkola))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nf_jComboBoxKierunek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf_jLabelKierunek))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(nf_jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nf_jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nf_jRadioButton3)
                            .addComponent(nf_jLabelKlasa)))
                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nf_jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nf_jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanel1Layout.createSequentialGroup()
                        .addComponent(nf_jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nf_jSliderLiczbaUczniow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanel1Layout.createSequentialGroup()
                        .addComponent(nf_jLabelZapisaneDane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nf_ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf_jLabel7LiczbaUczniow))
                        .addContainerGap())))
        );

        nf_Plik.setText("Plik");

        nf_Zapisz.setText("Zapisz");
        nf_Plik.add(nf_Zapisz);

        nf_Wczytaj.setText("Wczytaj");
        nf_Plik.add(nf_Wczytaj);

        nf_Zamknij.setText("Zamknij");
        nf_Zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_ZamknijActionPerformed(evt);
            }
        });
        nf_Plik.add(nf_Zamknij);

        nf_menubar.add(nf_Plik);

        nf_Edycja.setText("Edycja");

        nf_ZmienCzcionke.setText("Zmień czcionkę");
        nf_Edycja.add(nf_ZmienCzcionke);

        nf_ZmienTlo.setText("Zmiań tło");

        nf_tloNiebieski.setText("Niebieski");
        nf_tloNiebieski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_tloNiebieskiActionPerformed(evt);
            }
        });
        nf_ZmienTlo.add(nf_tloNiebieski);

        nf_tloZielony.setText("Zielony");
        nf_tloZielony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_tloZielonyActionPerformed(evt);
            }
        });
        nf_ZmienTlo.add(nf_tloZielony);

        nf_tloBialy.setText("Bialy");
        nf_tloBialy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_tloBialyActionPerformed(evt);
            }
        });
        nf_ZmienTlo.add(nf_tloBialy);

        nf_tloDefault.setText("Default");
        nf_tloDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_tloDefaultActionPerformed(evt);
            }
        });
        nf_ZmienTlo.add(nf_tloDefault);

        nf_Edycja.add(nf_ZmienTlo);

        nf_menubar.add(nf_Edycja);

        nf_OProgramie.setText("O programie");

        nf_OProgramieMeniuItem.setText("O programie");
        nf_OProgramieMeniuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_OProgramieMeniuItemActionPerformed(evt);
            }
        });
        nf_OProgramie.add(nf_OProgramieMeniuItem);

        nf_Help.setText("Help");
        nf_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_HelpActionPerformed(evt);
            }
        });
        nf_OProgramie.add(nf_Help);

        nf_menubar.add(nf_OProgramie);

        setJMenuBar(nf_menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nf_jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nf_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nf_jComboBoxSzkolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_jComboBoxSzkolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nf_jComboBoxSzkolaActionPerformed

    private void nf_OProgramieMeniuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_OProgramieMeniuItemActionPerformed
        JOptionPane.showMessageDialog(null,"Program zrobil NORBERT FICNER");
    }//GEN-LAST:event_nf_OProgramieMeniuItemActionPerformed

    private void nf_ZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_ZamknijActionPerformed
        System.exit(1);
    }//GEN-LAST:event_nf_ZamknijActionPerformed

    private void nf_tloNiebieskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_tloNiebieskiActionPerformed
        nf_jPanel1.setBackground(Color.blue);
    }//GEN-LAST:event_nf_tloNiebieskiActionPerformed

    private void nf_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_HelpActionPerformed
        JOptionPane.showMessageDialog(null,"Cos tu by moglo byc ale nie wiem co");
    }//GEN-LAST:event_nf_HelpActionPerformed

    private void nf_tloZielonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_tloZielonyActionPerformed
        nf_jPanel1.setBackground(Color.green);
    }//GEN-LAST:event_nf_tloZielonyActionPerformed

    private void nf_tloBialyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_tloBialyActionPerformed
        nf_jPanel1.setBackground(Color.white);
    }//GEN-LAST:event_nf_tloBialyActionPerformed

    private void nf_tloDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_tloDefaultActionPerformed
        nf_jPanel1.setBackground(Color.gray);
    }//GEN-LAST:event_nf_tloDefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjektProgram().setVisible(true);
            }
        });
    }
    String AbsolutePathToResources = "C:\\Users\\zalman\\Documents\\NetBeansProjects\\ProjektWlasnyProgram\\src\\main\\java\\com\\mycompany\\projektwlasnyprogram\\resources\\LogoProgramu.png";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu nf_Edycja;
    private javax.swing.JMenuItem nf_Help;
    private javax.swing.JMenu nf_OProgramie;
    private javax.swing.JMenuItem nf_OProgramieMeniuItem;
    private javax.swing.JMenu nf_Plik;
    private javax.swing.JScrollPane nf_ScrollPane1;
    private javax.swing.JMenuItem nf_Wczytaj;
    private javax.swing.JMenuItem nf_Zamknij;
    private javax.swing.JMenuItem nf_Zapisz;
    private javax.swing.JMenuItem nf_ZmienCzcionke;
    private javax.swing.JMenu nf_ZmienTlo;
    private javax.swing.ButtonGroup nf_buttonGroupKlasa;
    private javax.swing.JComboBox<String> nf_jComboBoxKierunek;
    private javax.swing.JComboBox<String> nf_jComboBoxSzkola;
    private javax.swing.JLabel nf_jLabel7LiczbaUczniow;
    private javax.swing.JLabel nf_jLabelImie;
    private javax.swing.JLabel nf_jLabelKierunek;
    private javax.swing.JLabel nf_jLabelKlasa;
    private javax.swing.JLabel nf_jLabelLogo;
    private javax.swing.JLabel nf_jLabelNazwisko;
    private javax.swing.JLabel nf_jLabelSzkola;
    private javax.swing.JLabel nf_jLabelZapisaneDane;
    private javax.swing.JPanel nf_jPanel1;
    private javax.swing.JRadioButton nf_jRadioButton1;
    private javax.swing.JRadioButton nf_jRadioButton2;
    private javax.swing.JRadioButton nf_jRadioButton3;
    private javax.swing.JRadioButton nf_jRadioButton4;
    private javax.swing.JRadioButton nf_jRadioButton5;
    private javax.swing.JSlider nf_jSliderLiczbaUczniow;
    private javax.swing.JTextArea nf_jTextAreaWczytaneDane;
    private javax.swing.JTextField nf_jTextFieldImie;
    private javax.swing.JTextField nf_jTextFieldNazwisko;
    private javax.swing.JMenuBar nf_menubar;
    private javax.swing.JMenuItem nf_tloBialy;
    private javax.swing.JMenuItem nf_tloDefault;
    private javax.swing.JMenuItem nf_tloNiebieski;
    private javax.swing.JMenuItem nf_tloZielony;
    // End of variables declaration//GEN-END:variables
}
