/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.przelicznikjenostekprojekt;

/**
 *
 * @author zalman
 */
public class PrzelicznikJednostekProjekt extends javax.swing.JFrame {

    /**
     * Creates new form PrzelicznikJednostekProjekt
     */
    public PrzelicznikJednostekProjekt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nf_buttonGroup1 = new javax.swing.ButtonGroup();
        nf_buttonGroup2 = new javax.swing.ButtonGroup();
        nf_buttonGroup3 = new javax.swing.ButtonGroup();
        nf_buttonGroup4 = new javax.swing.ButtonGroup();
        nf_jTabbedPaneOdleglosc = new javax.swing.JTabbedPane();
        nf_jPanelOdleglosc = new javax.swing.JPanel();
        nf_jLabelWprowadzOdleglosc = new javax.swing.JLabel();
        nf_jLabelPrzeliczonaOdleglosc = new javax.swing.JLabel();
        nf_jLabelPrzeliczonaOdlegloscWynik = new javax.swing.JLabel();
        nf_jButtonObliczOdleglosc = new javax.swing.JButton();
        nf_jSpinnerWprowadzonaOdleglosc = new javax.swing.JSpinner();
        nf_jRadioButtonMet2 = new javax.swing.JRadioButton();
        nf_jRadioButtonKMet1 = new javax.swing.JRadioButton();
        nf_jRadioButtonCal1 = new javax.swing.JRadioButton();
        nf_jRadioButtonMet1 = new javax.swing.JRadioButton();
        nf_jRadioButtonKMet2 = new javax.swing.JRadioButton();
        nf_jRadioButtonCal2 = new javax.swing.JRadioButton();
        nf_jPanelTemperatura = new javax.swing.JPanel();
        nf_jLabelWprowadztemperature = new javax.swing.JLabel();
        nf_jLabelPrzeliczonaTemperatura = new javax.swing.JLabel();
        nf_jLabelPrzeliczonaTemperaturaWynik = new javax.swing.JLabel();
        nf_jButtonObliczTemperature = new javax.swing.JButton();
        nf_jSpinnerWprowadzonaTemperatura = new javax.swing.JSpinner();
        nf_jRadioButtonCel1 = new javax.swing.JRadioButton();
        nf_jRadioButtonKal1 = new javax.swing.JRadioButton();
        nf_jRadioButtonFar1 = new javax.swing.JRadioButton();
        nf_jRadioButtonCel2 = new javax.swing.JRadioButton();
        nf_jRadioButtonKal2 = new javax.swing.JRadioButton();
        nf_jRadioButtonFar2 = new javax.swing.JRadioButton();
        nf_jMenuBar = new javax.swing.JMenuBar();
        nf_jMenuPlik = new javax.swing.JMenu();
        nf_jMenuItemZapisz = new javax.swing.JMenuItem();
        nf_jMenuItemZamknij = new javax.swing.JMenuItem();
        nf_jMenuOProgramie = new javax.swing.JMenu();
        nf_jMenuItemOProgramie = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nf_jLabelWprowadzOdleglosc.setText("Wprowadż odległość:");

        nf_jLabelPrzeliczonaOdleglosc.setText("Przeliczona odległość:");

        nf_jButtonObliczOdleglosc.setText("Oblicz");
        nf_jButtonObliczOdleglosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_jButtonObliczOdlegloscActionPerformed(evt);
            }
        });

        nf_buttonGroup4.add(nf_jRadioButtonMet2);
        nf_jRadioButtonMet2.setText("Metry");

        nf_buttonGroup3.add(nf_jRadioButtonKMet1);
        nf_jRadioButtonKMet1.setText("Kilometry");

        nf_buttonGroup3.add(nf_jRadioButtonCal1);
        nf_jRadioButtonCal1.setText("Cale");

        nf_buttonGroup3.add(nf_jRadioButtonMet1);
        nf_jRadioButtonMet1.setText("Metry");

        nf_buttonGroup4.add(nf_jRadioButtonKMet2);
        nf_jRadioButtonKMet2.setText("Kilometry");

        nf_buttonGroup4.add(nf_jRadioButtonCal2);
        nf_jRadioButtonCal2.setText("Cale");

        javax.swing.GroupLayout nf_jPanelOdlegloscLayout = new javax.swing.GroupLayout(nf_jPanelOdleglosc);
        nf_jPanelOdleglosc.setLayout(nf_jPanelOdlegloscLayout);
        nf_jPanelOdlegloscLayout.setHorizontalGroup(
            nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nf_jPanelOdlegloscLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nf_jPanelOdlegloscLayout.createSequentialGroup()
                        .addComponent(nf_jLabelWprowadzOdleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(nf_jSpinnerWprowadzonaOdleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nf_jPanelOdlegloscLayout.createSequentialGroup()
                        .addComponent(nf_jLabelPrzeliczonaOdleglosc)
                        .addGap(18, 18, 18)
                        .addComponent(nf_jLabelPrzeliczonaOdlegloscWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nf_jPanelOdlegloscLayout.createSequentialGroup()
                                .addComponent(nf_jRadioButtonMet2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nf_jRadioButtonKMet2))
                            .addGroup(nf_jPanelOdlegloscLayout.createSequentialGroup()
                                .addComponent(nf_jRadioButtonMet1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nf_jRadioButtonKMet1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nf_jRadioButtonCal1)
                    .addComponent(nf_jRadioButtonCal2))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanelOdlegloscLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nf_jButtonObliczOdleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        nf_jPanelOdlegloscLayout.setVerticalGroup(
            nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nf_jPanelOdlegloscLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nf_jPanelOdlegloscLayout.createSequentialGroup()
                        .addGroup(nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nf_jLabelWprowadzOdleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nf_jSpinnerWprowadzonaOdleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nf_jLabelPrzeliczonaOdleglosc)
                            .addComponent(nf_jLabelPrzeliczonaOdlegloscWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(nf_jButtonObliczOdleglosc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nf_jPanelOdlegloscLayout.createSequentialGroup()
                        .addGroup(nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nf_jRadioButtonMet1)
                            .addComponent(nf_jRadioButtonKMet1)
                            .addComponent(nf_jRadioButtonCal1))
                        .addGap(18, 18, 18)
                        .addGroup(nf_jPanelOdlegloscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nf_jRadioButtonMet2)
                            .addComponent(nf_jRadioButtonKMet2)
                            .addComponent(nf_jRadioButtonCal2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        nf_jTabbedPaneOdleglosc.addTab("Odległość", nf_jPanelOdleglosc);

        nf_jLabelWprowadztemperature.setText("Wprowadż temperature:");

        nf_jLabelPrzeliczonaTemperatura.setText("Przeliczona temperatura:");

        nf_jButtonObliczTemperature.setText("Oblicz");
        nf_jButtonObliczTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_jButtonObliczTemperatureActionPerformed(evt);
            }
        });

        nf_buttonGroup1.add(nf_jRadioButtonCel1);
        nf_jRadioButtonCel1.setText("C");

        nf_buttonGroup1.add(nf_jRadioButtonKal1);
        nf_jRadioButtonKal1.setText("K");

        nf_buttonGroup1.add(nf_jRadioButtonFar1);
        nf_jRadioButtonFar1.setText("F");

        nf_buttonGroup2.add(nf_jRadioButtonCel2);
        nf_jRadioButtonCel2.setText("C");

        nf_buttonGroup2.add(nf_jRadioButtonKal2);
        nf_jRadioButtonKal2.setText("K");

        nf_buttonGroup2.add(nf_jRadioButtonFar2);
        nf_jRadioButtonFar2.setText("F");
        nf_jRadioButtonFar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_jRadioButtonFar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nf_jPanelTemperaturaLayout = new javax.swing.GroupLayout(nf_jPanelTemperatura);
        nf_jPanelTemperatura.setLayout(nf_jPanelTemperaturaLayout);
        nf_jPanelTemperaturaLayout.setHorizontalGroup(
            nf_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanelTemperaturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nf_jButtonObliczTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(nf_jPanelTemperaturaLayout.createSequentialGroup()
                .addGroup(nf_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(nf_jPanelTemperaturaLayout.createSequentialGroup()
                        .addComponent(nf_jLabelWprowadztemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nf_jSpinnerWprowadzonaTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nf_jRadioButtonCel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nf_jRadioButtonKal1)
                        .addGap(18, 18, 18)
                        .addComponent(nf_jRadioButtonFar1))
                    .addGroup(nf_jPanelTemperaturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nf_jLabelPrzeliczonaTemperatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nf_jLabelPrzeliczonaTemperaturaWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nf_jRadioButtonCel2)
                        .addGap(18, 18, 18)
                        .addComponent(nf_jRadioButtonKal2)
                        .addGap(18, 18, 18)
                        .addComponent(nf_jRadioButtonFar2)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        nf_jPanelTemperaturaLayout.setVerticalGroup(
            nf_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nf_jPanelTemperaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nf_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nf_jLabelWprowadztemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nf_jSpinnerWprowadzonaTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nf_jRadioButtonCel1)
                    .addComponent(nf_jRadioButtonKal1)
                    .addComponent(nf_jRadioButtonFar1))
                .addGap(38, 38, 38)
                .addGroup(nf_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nf_jLabelPrzeliczonaTemperatura)
                    .addComponent(nf_jLabelPrzeliczonaTemperaturaWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nf_jPanelTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nf_jRadioButtonCel2)
                        .addComponent(nf_jRadioButtonKal2)
                        .addComponent(nf_jRadioButtonFar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(nf_jButtonObliczTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nf_jTabbedPaneOdleglosc.addTab("Temperatura", nf_jPanelTemperatura);

        nf_jMenuPlik.setText("Plik");

        nf_jMenuItemZapisz.setText("Zapisz");
        nf_jMenuPlik.add(nf_jMenuItemZapisz);

        nf_jMenuItemZamknij.setText("Zamknij");
        nf_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_jMenuItemZamknijActionPerformed(evt);
            }
        });
        nf_jMenuPlik.add(nf_jMenuItemZamknij);

        nf_jMenuBar.add(nf_jMenuPlik);

        nf_jMenuOProgramie.setText("O programie");

        nf_jMenuItemOProgramie.setText("O programie");
        nf_jMenuOProgramie.add(nf_jMenuItemOProgramie);

        nf_jMenuBar.add(nf_jMenuOProgramie);

        setJMenuBar(nf_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nf_jTabbedPaneOdleglosc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nf_jTabbedPaneOdleglosc))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nf_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_nf_jMenuItemZamknijActionPerformed

    private void nf_jButtonObliczTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_jButtonObliczTemperatureActionPerformed
        if(nf_jRadioButtonCel1.isSelected() && nf_jRadioButtonCel2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            int nfprzeliczona = nfwartosc * 1;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);
        } 
        if(nf_jRadioButtonCel1.isSelected() && nf_jRadioButtonKal2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            double nfprzeliczona = nfwartosc + 274.15;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);
        }
         if(nf_jRadioButtonCel1.isSelected() && nf_jRadioButtonFar2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            double nfprzeliczona = nfwartosc * 9 / 5 + 32;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);        
        }
         if(nf_jRadioButtonKal1.isSelected() && nf_jRadioButtonKal2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            int nfprzeliczona = nfwartosc * 1;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);        
        }
         
        if(nf_jRadioButtonKal1.isSelected() && nf_jRadioButtonCel2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            double nfprzeliczona = nfwartosc - 274.15;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonKal1.isSelected() && nf_jRadioButtonFar2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            double nfprzeliczona = nfwartosc * 1.8 - 459.67;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonFar1.isSelected() && nf_jRadioButtonCel2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            double nfprzeliczona = nfwartosc * 0.56 - 17.78;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonFar1.isSelected() && nf_jRadioButtonKal2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            double nfprzeliczona = nfwartosc * 0.56 + 255.37;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonFar1.isSelected() && nf_jRadioButtonFar2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaTemperatura.getValue();
            int nfprzeliczona = nfwartosc * 1;
            
            nf_jLabelPrzeliczonaTemperaturaWynik.setText(""+ nfprzeliczona);        
        }
       
    }//GEN-LAST:event_nf_jButtonObliczTemperatureActionPerformed

    private void nf_jButtonObliczOdlegloscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_jButtonObliczOdlegloscActionPerformed
        if(nf_jRadioButtonMet1.isSelected() && nf_jRadioButtonMet2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            int nfprzeliczona = nfwartosc * 1;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonMet1.isSelected() && nf_jRadioButtonKMet2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            double nfprzeliczona = nfwartosc * 0.001;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonMet1.isSelected() && nf_jRadioButtonCal2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            double nfprzeliczona = nfwartosc * 39.37;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonKMet1.isSelected() && nf_jRadioButtonMet2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            double nfprzeliczona = nfwartosc * 1000;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonKMet1.isSelected() && nf_jRadioButtonKMet2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            int nfprzeliczona = nfwartosc * 1;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonKMet1.isSelected() && nf_jRadioButtonCal2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            double nfprzeliczona = nfwartosc * 39370.07;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
        if(nf_jRadioButtonCal1.isSelected() && nf_jRadioButtonMet2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            double nfprzeliczona = nfwartosc * 0.0254;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
          if(nf_jRadioButtonCal1.isSelected() && nf_jRadioButtonKMet2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            double nfprzeliczona = nfwartosc * 0.0254 * 0.001;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
            if(nf_jRadioButtonCal1.isSelected() && nf_jRadioButtonCal2.isSelected() ){
            int nfwartosc = (int) nf_jSpinnerWprowadzonaOdleglosc.getValue();
            int nfprzeliczona = nfwartosc * 1;
            
            nf_jLabelPrzeliczonaOdlegloscWynik.setText(""+ nfprzeliczona);        
        }
        

     
    }//GEN-LAST:event_nf_jButtonObliczOdlegloscActionPerformed

    private void nf_jRadioButtonFar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_jRadioButtonFar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nf_jRadioButtonFar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrzelicznikJednostekProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrzelicznikJednostekProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrzelicznikJednostekProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrzelicznikJednostekProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrzelicznikJednostekProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup nf_buttonGroup1;
    private javax.swing.ButtonGroup nf_buttonGroup2;
    private javax.swing.ButtonGroup nf_buttonGroup3;
    private javax.swing.ButtonGroup nf_buttonGroup4;
    private javax.swing.JButton nf_jButtonObliczOdleglosc;
    private javax.swing.JButton nf_jButtonObliczTemperature;
    private javax.swing.JLabel nf_jLabelPrzeliczonaOdleglosc;
    private javax.swing.JLabel nf_jLabelPrzeliczonaOdlegloscWynik;
    private javax.swing.JLabel nf_jLabelPrzeliczonaTemperatura;
    private javax.swing.JLabel nf_jLabelPrzeliczonaTemperaturaWynik;
    private javax.swing.JLabel nf_jLabelWprowadzOdleglosc;
    private javax.swing.JLabel nf_jLabelWprowadztemperature;
    private javax.swing.JMenuBar nf_jMenuBar;
    private javax.swing.JMenuItem nf_jMenuItemOProgramie;
    private javax.swing.JMenuItem nf_jMenuItemZamknij;
    private javax.swing.JMenuItem nf_jMenuItemZapisz;
    private javax.swing.JMenu nf_jMenuOProgramie;
    private javax.swing.JMenu nf_jMenuPlik;
    private javax.swing.JPanel nf_jPanelOdleglosc;
    private javax.swing.JPanel nf_jPanelTemperatura;
    private javax.swing.JRadioButton nf_jRadioButtonCal1;
    private javax.swing.JRadioButton nf_jRadioButtonCal2;
    private javax.swing.JRadioButton nf_jRadioButtonCel1;
    private javax.swing.JRadioButton nf_jRadioButtonCel2;
    private javax.swing.JRadioButton nf_jRadioButtonFar1;
    private javax.swing.JRadioButton nf_jRadioButtonFar2;
    private javax.swing.JRadioButton nf_jRadioButtonKMet1;
    private javax.swing.JRadioButton nf_jRadioButtonKMet2;
    private javax.swing.JRadioButton nf_jRadioButtonKal1;
    private javax.swing.JRadioButton nf_jRadioButtonKal2;
    private javax.swing.JRadioButton nf_jRadioButtonMet1;
    private javax.swing.JRadioButton nf_jRadioButtonMet2;
    private javax.swing.JSpinner nf_jSpinnerWprowadzonaOdleglosc;
    private javax.swing.JSpinner nf_jSpinnerWprowadzonaTemperatura;
    private javax.swing.JTabbedPane nf_jTabbedPaneOdleglosc;
    // End of variables declaration//GEN-END:variables
}
