/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kalkulator;

/**
 *
 * @author zalman
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nf_jPanel1 = new javax.swing.JPanel();
        nf_jTextFieldObliczenia = new javax.swing.JTextField();
        nf_jButton7 = new javax.swing.JButton();
        nf_jButton4 = new javax.swing.JButton();
        nf_jButton1 = new javax.swing.JButton();
        nf_jButton2 = new javax.swing.JButton();
        nf_jButton5 = new javax.swing.JButton();
        nf_jButton8 = new javax.swing.JButton();
        nf_jButton9 = new javax.swing.JButton();
        nf_jButton6 = new javax.swing.JButton();
        nf_jButton3 = new javax.swing.JButton();
        nf_jButton0 = new javax.swing.JButton();
        nf_jButtonCE = new javax.swing.JButton();
        nf_jButtonPlusMinus = new javax.swing.JButton();
        nf_jButtonPrzecinek = new javax.swing.JButton();
        nf_jButtonDodawanie = new javax.swing.JButton();
        nf_jButtonDzielenie = new javax.swing.JButton();
        nf_jButtonMnozenie = new javax.swing.JButton();
        nf_jButtonOdejmowanie = new javax.swing.JButton();
        nf_jButtonPierwiastkowanie = new javax.swing.JButton();
        nf_jButtonPiotegowanie = new javax.swing.JButton();
        nf_jButtonRowna = new javax.swing.JButton();
        nf_jMenuBar = new javax.swing.JMenuBar();
        nf_jMenuPlik = new javax.swing.JMenu();
        nf_jCheckBoxMenuItemZapis = new javax.swing.JCheckBoxMenuItem();
        nf_jMenuItemZamknij = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nf_jButton7.setText("7");

        nf_jButton4.setText("4");

        nf_jButton1.setText("1");

        nf_jButton2.setText("2");

        nf_jButton5.setText("5");

        nf_jButton8.setText("8");

        nf_jButton9.setText("9");

        nf_jButton6.setText("6");

        nf_jButton3.setText("3");

        nf_jButton0.setText("0");

        nf_jButtonCE.setText("CE");

        nf_jButtonPlusMinus.setText("+-");

        nf_jButtonPrzecinek.setText(",");

        nf_jButtonDodawanie.setText("+");

        nf_jButtonDzielenie.setText("/");

        nf_jButtonMnozenie.setText("*");

        nf_jButtonOdejmowanie.setText("-");

        nf_jButtonPierwiastkowanie.setText("√");

        nf_jButtonPiotegowanie.setText("pot.");

        nf_jButtonRowna.setText("=");

        javax.swing.GroupLayout nf_jPanel1Layout = new javax.swing.GroupLayout(nf_jPanel1);
        nf_jPanel1.setLayout(nf_jPanel1Layout);
        nf_jPanel1Layout.setHorizontalGroup(
            nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nf_jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nf_jTextFieldObliczenia)
                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                .addComponent(nf_jButtonPrzecinek, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                        .addComponent(nf_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nf_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                        .addComponent(nf_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nf_jButtonPiotegowanie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nf_jButtonPierwiastkowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nf_jButtonOdejmowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                    .addComponent(nf_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nf_jButtonDodawanie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                    .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                            .addComponent(nf_jButtonPlusMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nf_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nf_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                            .addComponent(nf_jButtonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nf_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nf_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                            .addComponent(nf_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nf_jButtonDzielenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                            .addComponent(nf_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nf_jButtonMnozenie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nf_jButtonRowna, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nf_jPanel1Layout.setVerticalGroup(
            nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nf_jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nf_jTextFieldObliczenia, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nf_jPanel1Layout.createSequentialGroup()
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nf_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nf_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nf_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nf_jButtonCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nf_jButtonMnozenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nf_jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nf_jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(nf_jPanel1Layout.createSequentialGroup()
                                .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nf_jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(nf_jButtonPlusMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nf_jButtonDzielenie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nf_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(nf_jButtonPrzecinek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nf_jButtonDodawanie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nf_jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nf_jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nf_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nf_jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(nf_jButtonOdejmowanie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nf_jButtonPiotegowanie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nf_jButtonPierwiastkowanie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(nf_jButtonRowna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        nf_jMenuPlik.setText("Plik");

        nf_jCheckBoxMenuItemZapis.setSelected(true);
        nf_jCheckBoxMenuItemZapis.setText("Zapis historii działań");
        nf_jCheckBoxMenuItemZapis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_jCheckBoxMenuItemZapisActionPerformed(evt);
            }
        });
        nf_jMenuPlik.add(nf_jCheckBoxMenuItemZapis);

        nf_jMenuItemZamknij.setText("Zamknij");
        nf_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf_jMenuItemZamknijActionPerformed(evt);
            }
        });
        nf_jMenuPlik.add(nf_jMenuItemZamknij);

        nf_jMenuBar.add(nf_jMenuPlik);

        setJMenuBar(nf_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nf_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nf_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nf_jCheckBoxMenuItemZapisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_jCheckBoxMenuItemZapisActionPerformed
    }//GEN-LAST:event_nf_jCheckBoxMenuItemZapisActionPerformed

    private void nf_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_nf_jMenuItemZamknijActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nf_jButton0;
    private javax.swing.JButton nf_jButton1;
    private javax.swing.JButton nf_jButton2;
    private javax.swing.JButton nf_jButton3;
    private javax.swing.JButton nf_jButton4;
    private javax.swing.JButton nf_jButton5;
    private javax.swing.JButton nf_jButton6;
    private javax.swing.JButton nf_jButton7;
    private javax.swing.JButton nf_jButton8;
    private javax.swing.JButton nf_jButton9;
    private javax.swing.JButton nf_jButtonCE;
    private javax.swing.JButton nf_jButtonDodawanie;
    private javax.swing.JButton nf_jButtonDzielenie;
    private javax.swing.JButton nf_jButtonMnozenie;
    private javax.swing.JButton nf_jButtonOdejmowanie;
    private javax.swing.JButton nf_jButtonPierwiastkowanie;
    private javax.swing.JButton nf_jButtonPiotegowanie;
    private javax.swing.JButton nf_jButtonPlusMinus;
    private javax.swing.JButton nf_jButtonPrzecinek;
    private javax.swing.JButton nf_jButtonRowna;
    private javax.swing.JCheckBoxMenuItem nf_jCheckBoxMenuItemZapis;
    private javax.swing.JMenuBar nf_jMenuBar;
    private javax.swing.JMenuItem nf_jMenuItemZamknij;
    private javax.swing.JMenu nf_jMenuPlik;
    private javax.swing.JPanel nf_jPanel1;
    private javax.swing.JTextField nf_jTextFieldObliczenia;
    // End of variables declaration//GEN-END:variables
}
